[tool.poetry]
name = "aiohttp-rpc"
version = "0.1.0"
description = ""
authors = ["expert-m <michael@sulyak.info>"]

[tool.poetry.dependencies]
python = "^3.6"
aiohttp = "^3.6.2"

[tool.poetry.dev-dependencies]
pytest = "^6.0.1"
tox = "^3.19.0"
pytest-asyncio = "^0.14.0"
pytest-aiohttp = "^0.3.0"
pytest-mock = "^3.2.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
